# Generated by Django 3.2.9 on 2021-12-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssource',
            old_name='id',
            new_name='srcid',
        ),
    ]
