# Generated by Django 3.2.9 on 2021-12-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_id_newssource_srcid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssource',
            old_name='srcid',
            new_name='id',
        ),
    ]
